// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCS.DAL.Data;

#nullable disable

namespace SCS.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240424210837_ini2")]
    partial class ini2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SCS.DAL.Entites.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ClassSopervisor")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__CB1927C0A43DC339");

                    b.HasIndex("ClassSopervisor");

                    b.HasIndex("LevelId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SCS.DAL.Entites.ClassChat", b =>
                {
                    b.Property<int>("ClassChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassChatId"));

                    b.Property<DateOnly>("ClassChatDate")
                        .HasColumnType("date");

                    b.Property<string>("ClassChatFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassChatImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassChatText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Classid")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("ClassChatId")
                        .HasName("PK__ClassCha__366737B7853C99E7");

                    b.HasIndex("Classid");

                    b.HasIndex("StudentId");

                    b.ToTable("ClassChats");
                });

            modelBuilder.Entity("SCS.DAL.Entites.DegreeFile", b =>
                {
                    b.Property<int>("DegreeFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DegreeFileId"));

                    b.Property<string>("DegreeFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DegreeFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DegreeTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.HasKey("DegreeFileId")
                        .HasName("PK__DegreeFi__BE204451D78EA090");

                    b.HasIndex("DegreeTypeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TermId");

                    b.ToTable("DegreeFiles");
                });

            modelBuilder.Entity("SCS.DAL.Entites.DegreeType", b =>
                {
                    b.Property<int>("DegreeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DegreeTypeId"));

                    b.Property<string>("DegreeTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DegreeTypeId")
                        .HasName("PK__DegreeTy__DD0FA03F989A78C7");

                    b.ToTable("DegreeTypes");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BED2D6C38DB");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("SCS.DAL.Entites.FollowUpNoteBook", b =>
                {
                    b.Property<int>("FollowUpNoteBookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FollowUpNoteBookId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FollowUpNoteBookDate")
                        .HasColumnType("date");

                    b.Property<string>("FollowUpNoteBookText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectClassId")
                        .HasColumnType("int");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.HasKey("FollowUpNoteBookId")
                        .HasName("PK__FollowUp__64828509BE018E62");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectClassId");

                    b.HasIndex("TermId");

                    b.ToTable("FollowUpNoteBooks");
                });

            modelBuilder.Entity("SCS.DAL.Entites.HomeWork", b =>
                {
                    b.Property<int>("HomeWorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomeWorkId"));

                    b.Property<DateOnly>("HomeWorkDate")
                        .HasColumnType("date");

                    b.Property<decimal>("HomeWorkDegree")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("HomeWorkFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeWorkImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeWorkText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeWorkTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HomeWorkdescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectClassId")
                        .HasColumnType("int");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.HasKey("HomeWorkId")
                        .HasName("PK__HomeWork__C49C7058C45406AA");

                    b.HasIndex("SubjectClassId");

                    b.HasIndex("TermId");

                    b.ToTable("HomeWorks");
                });

            modelBuilder.Entity("SCS.DAL.Entites.LaibaryBook", b =>
                {
                    b.Property<int>("LaibaryBookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LaibaryBookId"));

                    b.Property<string>("LaibaryBookName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LaibaryBookPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sectionid")
                        .HasColumnType("int");

                    b.HasKey("LaibaryBookId")
                        .HasName("PK__LaibaryB__FC3D9298FAEF7CC5");

                    b.HasIndex("Sectionid");

                    b.ToTable("LaibaryBooks");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LevelId")
                        .HasName("PK__Levels__09F03C26DD3AFEE2");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateOnly>("NotificationDate")
                        .HasColumnType("date");

                    b.Property<string>("NotificationImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E12C5C02ECF");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SCS.DAL.Entites.NotificationRole", b =>
                {
                    b.Property<int>("NotificationRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationRoleId"));

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<string>("NotificationRoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("NotificationRoleId")
                        .HasName("PK__Notifica__D523AA9054D92CD0");

                    b.HasIndex("NotificationId");

                    b.HasIndex("RoleId");

                    b.ToTable("NotificationRoles");
                });

            modelBuilder.Entity("SCS.DAL.Entites.ParentSubervaisorChat", b =>
                {
                    b.Property<int>("ParentSubervaisorChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParentSubervaisorChatId"));

                    b.Property<DateOnly>("ParentSubervaisorChatDate")
                        .HasColumnType("date");

                    b.Property<string>("ParentSubervaisorChatFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentSubervaisorChatImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentSubervaisorChatText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Recever")
                        .HasColumnType("int");

                    b.Property<int>("Sender")
                        .HasColumnType("int");

                    b.HasKey("ParentSubervaisorChatId")
                        .HasName("PK__ParentSu__5CE078C8914C6D9B");

                    b.HasIndex("Recever");

                    b.HasIndex("Sender");

                    b.ToTable("ParentSubervaisorChats");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Reinforcementlesson", b =>
                {
                    b.Property<int>("ReinforcementlessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReinforcementlessonId"));

                    b.Property<DateOnly?>("ReinforcementlessonDate")
                        .HasColumnType("date");

                    b.Property<string>("ReinforcementlessonFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReinforcementlessonTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Reinforcementlessondescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reinforcementlessonlink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectClassId")
                        .HasColumnType("int");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.HasKey("ReinforcementlessonId")
                        .HasName("PK__Reinforc__B162A1F24B334BFB");

                    b.HasIndex("SubjectClassId");

                    b.HasIndex("TermId");

                    b.ToTable("Reinforcementlessons");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1AB92E2539");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SectionId")
                        .HasName("PK__Sections__80EF0872CDC94C33");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Solution", b =>
                {
                    b.Property<int>("SolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolutionId"));

                    b.Property<int>("HomeWorkId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SolutionDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("SolutionDegree")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("SolutionFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Solutionnote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("SolutionId")
                        .HasName("PK__Solution__6B633AD08345CAC6");

                    b.HasIndex("HomeWorkId");

                    b.HasIndex("StudentId");

                    b.ToTable("Solutions");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("StedentParent")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudentId")
                        .HasName("PK__Students__32C52B991EF14DA2");

                    b.HasIndex("ClassId");

                    b.HasIndex("StedentParent");

                    b.HasIndex("UserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SCS.DAL.Entites.StudentAttendance", b =>
                {
                    b.Property<int>("StudentAttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentAttendanceId"));

                    b.Property<DateOnly>("StudentAttendanceDate")
                        .HasColumnType("date");

                    b.Property<decimal>("StudentAttendanceValue")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.HasKey("StudentAttendanceId")
                        .HasName("PK__StudentA__6342645B998B6F8C");

                    b.HasIndex("StudentId");

                    b.HasIndex("TermId");

                    b.ToTable("StudentAttendances");
                });

            modelBuilder.Entity("SCS.DAL.Entites.StudentDegree", b =>
                {
                    b.Property<int>("StudentDegreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentDegreeId"));

                    b.Property<int>("DegreeTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("StudentDegreeValue")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("StudentDegreenote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectClassId")
                        .HasColumnType("int");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.HasKey("StudentDegreeId")
                        .HasName("PK__StudentD__0CC89BAD4CA02FF8");

                    b.HasIndex("DegreeTypeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectClassId");

                    b.HasIndex("TermId");

                    b.ToTable("StudentDegrees");
                });

            modelBuilder.Entity("SCS.DAL.Entites.StudentQeustion", b =>
                {
                    b.Property<int>("StudentQeustionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentQeustionId"));

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StudentQeustionDate")
                        .HasColumnType("date");

                    b.Property<string>("StudentQeustionImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentQeustionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectClassId")
                        .HasColumnType("int");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.HasKey("StudentQeustionId")
                        .HasName("PK__StudentQ__A171725E580C4668");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectClassId");

                    b.HasIndex("TermId");

                    b.ToTable("StudentQeustions");
                });

            modelBuilder.Entity("SCS.DAL.Entites.StudentSuggestion", b =>
                {
                    b.Property<int>("StudentSuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentSuggestionId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StudentSuggestionDate")
                        .HasColumnType("date");

                    b.Property<string>("StudentSuggestionImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentSuggestionText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentSuggestionId")
                        .HasName("PK__StudentS__699998993E593C88");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentSuggestions");
                });

            modelBuilder.Entity("SCS.DAL.Entites.StudentTimeTable", b =>
                {
                    b.Property<int>("StudentTimeTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentTimeTableId"));

                    b.Property<int>("Classid")
                        .HasColumnType("int");

                    b.Property<string>("StudentTimeTableImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentTimeTableId")
                        .HasName("PK__StudentT__AA15A797DF37C1F4");

                    b.HasIndex("Classid");

                    b.ToTable("StudentTimeTables");
                });

            modelBuilder.Entity("SCS.DAL.Entites.SubervisorNotification", b =>
                {
                    b.Property<int>("SubervisorNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubervisorNotificationId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.HasKey("SubervisorNotificationId")
                        .HasName("PK__Subervis__C7602C358A7AD4E2");

                    b.HasIndex("ClassId");

                    b.HasIndex("NotificationId");

                    b.ToTable("SubervisorNotifications");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectBook1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SubjectBook2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SubjectBook3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SubjectImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subjects__AC1BA3A827384BB8");

                    b.HasIndex("LevelId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SCS.DAL.Entites.SubjectClass", b =>
                {
                    b.Property<int>("SubjectClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectClassId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectTeacher")
                        .HasColumnType("int");

                    b.HasKey("SubjectClassId")
                        .HasName("PK__SubjectC__56E2859A3B35A6C6");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SubjectTeacher");

                    b.ToTable("SubjectClasses");
                });

            modelBuilder.Entity("SCS.DAL.Entites.TeacherAnswer", b =>
                {
                    b.Property<int>("TeacherAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherAnswerId"));

                    b.Property<int>("StudentQeustionId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("TeacherAnswerDate")
                        .HasColumnType("date");

                    b.Property<string>("TeacherAnswerImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherAnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherAnswerId")
                        .HasName("PK__TeacherA__A3B38DF996FAA0AC");

                    b.HasIndex("StudentQeustionId");

                    b.ToTable("TeacherAnswers");
                });

            modelBuilder.Entity("SCS.DAL.Entites.TeacherAttendance", b =>
                {
                    b.Property<int>("TeacherAttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherAttendanceId"));

                    b.Property<DateOnly>("TeacherAttendanceDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TeacherAttendanceValue")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TeacherAttendanceId")
                        .HasName("PK__TeacherA__678A48105127EB87");

                    b.HasIndex("UserId");

                    b.ToTable("TeacherAttendances");
                });

            modelBuilder.Entity("SCS.DAL.Entites.TeacherEvaluation", b =>
                {
                    b.Property<int>("TeacherEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherEvaluationId"));

                    b.Property<decimal>("TeacherEvaluationValue")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("TeacherEvaluationValueTow")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TeacherEvaluationId")
                        .HasName("PK__TeacherE__0F0C6E4734850A4E");

                    b.HasIndex("UserId");

                    b.ToTable("TeacherEvaluations");
                });

            modelBuilder.Entity("SCS.DAL.Entites.TeacherNotification", b =>
                {
                    b.Property<int>("TeacherNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherNotificationId"));

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectClassId")
                        .HasColumnType("int");

                    b.HasKey("TeacherNotificationId")
                        .HasName("PK__TeacherN__2AF3B401732B9ACC");

                    b.HasIndex("NotificationId");

                    b.HasIndex("SubjectClassId");

                    b.ToTable("TeacherNotifications");
                });

            modelBuilder.Entity("SCS.DAL.Entites.TeacherTimeTable", b =>
                {
                    b.Property<int>("TeacherTimeTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherTimeTableId"));

                    b.Property<string>("TeacherTimeTableImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TeacherTimeTableId")
                        .HasName("PK__TeacherT__466F62C46668223E");

                    b.HasIndex("UserId");

                    b.ToTable("TeacherTimeTables");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Term", b =>
                {
                    b.Property<int>("TermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TermId"));

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TermId")
                        .HasName("PK__Terms__410A21A58BFEAF71");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("SCS.DAL.Entites.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Usernumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Userpassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C467C8E13");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SCS.DAL.Entites.VclassDegree", b =>
                {
                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("TotalMarks")
                        .HasColumnType("decimal(38, 2)");

                    b.ToTable((string)null);

                    b.ToView("VClassDegrees", (string)null);
                });

            modelBuilder.Entity("SCS.DAL.Entites.VclassSubjectDegree", b =>
                {
                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SubjectClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("TotalMarks")
                        .HasColumnType("decimal(38, 2)");

                    b.ToTable((string)null);

                    b.ToView("VClassSubjectDegrees", (string)null);
                });

            modelBuilder.Entity("SCS.DAL.Entites.VclassSubjectTermDegree", b =>
                {
                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SubjectClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("TotalMarks")
                        .HasColumnType("decimal(38, 2)");

                    b.ToTable((string)null);

                    b.ToView("VClassSubjectTermDegrees", (string)null);
                });

            modelBuilder.Entity("SCS.DAL.Entites.VclassTermDegree", b =>
                {
                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("TotalMarks")
                        .HasColumnType("decimal(38, 2)");

                    b.ToTable((string)null);

                    b.ToView("VClassTermDegrees", (string)null);
                });

            modelBuilder.Entity("SCS.DAL.Entites.VteacherEvalution", b =>
                {
                    b.Property<decimal>("TeacherEvaluationValue")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("TeacherEvaluationValueTow")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.ToTable((string)null);

                    b.ToView("VTeacherEvalutions", (string)null);
                });

            modelBuilder.Entity("SCS.DAL.Entites.Class", b =>
                {
                    b.HasOne("SCS.DAL.Entites.User", "ClassSopervisorNavigation")
                        .WithMany("Classes")
                        .HasForeignKey("ClassSopervisor")
                        .IsRequired()
                        .HasConstraintName("FK__Classes__ClassSo__440B1D61");

                    b.HasOne("SCS.DAL.Entites.Level", "Level")
                        .WithMany("Classes")
                        .HasForeignKey("LevelId")
                        .IsRequired()
                        .HasConstraintName("FK__Classes__LevelId__4316F928");

                    b.Navigation("ClassSopervisorNavigation");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("SCS.DAL.Entites.ClassChat", b =>
                {
                    b.HasOne("SCS.DAL.Entites.Class", "Class")
                        .WithMany("ClassChats")
                        .HasForeignKey("Classid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ClassChat__Class__0F624AF8");

                    b.HasOne("SCS.DAL.Entites.Student", "Student")
                        .WithMany("ClassChats")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__ClassChat__Stude__10566F31");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SCS.DAL.Entites.DegreeFile", b =>
                {
                    b.HasOne("SCS.DAL.Entites.DegreeType", "DegreeType")
                        .WithMany("DegreeFiles")
                        .HasForeignKey("DegreeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DegreeFil__Degre__619B8048");

                    b.HasOne("SCS.DAL.Entites.Student", "Student")
                        .WithMany("DegreeFiles")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DegreeFil__Stude__628FA481");

                    b.HasOne("SCS.DAL.Entites.Term", "Term")
                        .WithMany("DegreeFiles")
                        .HasForeignKey("TermId")
                        .IsRequired()
                        .HasConstraintName("FK__DegreeFil__TermI__60A75C0F");

                    b.Navigation("DegreeType");

                    b.Navigation("Student");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("SCS.DAL.Entites.FollowUpNoteBook", b =>
                {
                    b.HasOne("SCS.DAL.Entites.Class", "Class")
                        .WithMany("FollowUpNoteBooks")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__FollowUpN__Class__75A278F5");

                    b.HasOne("SCS.DAL.Entites.SubjectClass", "SubjectClass")
                        .WithMany("FollowUpNoteBooks")
                        .HasForeignKey("SubjectClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FollowUpN__Subje__74AE54BC");

                    b.HasOne("SCS.DAL.Entites.Term", "Term")
                        .WithMany("FollowUpNoteBooks")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FollowUpN__TermI__76969D2E");

                    b.Navigation("Class");

                    b.Navigation("SubjectClass");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("SCS.DAL.Entites.HomeWork", b =>
                {
                    b.HasOne("SCS.DAL.Entites.SubjectClass", "SubjectClass")
                        .WithMany("HomeWorks")
                        .HasForeignKey("SubjectClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__HomeWorks__Subje__656C112C");

                    b.HasOne("SCS.DAL.Entites.Term", "Term")
                        .WithMany("HomeWorks")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__HomeWorks__TermI__66603565");

                    b.Navigation("SubjectClass");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("SCS.DAL.Entites.LaibaryBook", b =>
                {
                    b.HasOne("SCS.DAL.Entites.Section", "Section")
                        .WithMany("LaibaryBooks")
                        .HasForeignKey("Sectionid")
                        .IsRequired()
                        .HasConstraintName("FK__LaibaryBo__Secti__0C85DE4D");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Level", b =>
                {
                    b.HasOne("SCS.DAL.Entites.Department", "Department")
                        .WithMany("Levels")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Levels__Departme__403A8C7D");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Notification", b =>
                {
                    b.HasOne("SCS.DAL.Entites.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__17036CC0");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SCS.DAL.Entites.NotificationRole", b =>
                {
                    b.HasOne("SCS.DAL.Entites.Notification", "Notification")
                        .WithMany("NotificationRoles")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__Notif__19DFD96B");

                    b.HasOne("SCS.DAL.Entites.Role", "Role")
                        .WithMany("NotificationRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__RoleI__1AD3FDA4");

                    b.Navigation("Notification");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SCS.DAL.Entites.ParentSubervaisorChat", b =>
                {
                    b.HasOne("SCS.DAL.Entites.User", "ReceverNavigation")
                        .WithMany("ParentSubervaisorChatReceverNavigations")
                        .HasForeignKey("Recever")
                        .IsRequired()
                        .HasConstraintName("FK__ParentSub__Recev__14270015");

                    b.HasOne("SCS.DAL.Entites.User", "SenderNavigation")
                        .WithMany("ParentSubervaisorChatSenderNavigations")
                        .HasForeignKey("Sender")
                        .IsRequired()
                        .HasConstraintName("FK__ParentSub__Sende__1332DBDC");

                    b.Navigation("ReceverNavigation");

                    b.Navigation("SenderNavigation");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Reinforcementlesson", b =>
                {
                    b.HasOne("SCS.DAL.Entites.SubjectClass", "SubjectClass")
                        .WithMany("Reinforcementlessons")
                        .HasForeignKey("SubjectClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Reinforce__Subje__7D439ABD");

                    b.HasOne("SCS.DAL.Entites.Term", "Term")
                        .WithMany("Reinforcementlessons")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Reinforce__TermI__7E37BEF6");

                    b.Navigation("SubjectClass");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Solution", b =>
                {
                    b.HasOne("SCS.DAL.Entites.HomeWork", "HomeWork")
                        .WithMany("Solutions")
                        .HasForeignKey("HomeWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Solutions__HomeW__693CA210");

                    b.HasOne("SCS.DAL.Entites.Student", "Student")
                        .WithMany("Solutions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Solutions__Stude__6A30C649");

                    b.Navigation("HomeWork");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Student", b =>
                {
                    b.HasOne("SCS.DAL.Entites.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__Students__ClassI__5070F446");

                    b.HasOne("SCS.DAL.Entites.User", "StedentParentNavigation")
                        .WithMany("StudentStedentParentNavigations")
                        .HasForeignKey("StedentParent")
                        .IsRequired()
                        .HasConstraintName("FK__Students__Steden__4F7CD00D");

                    b.HasOne("SCS.DAL.Entites.User", "User")
                        .WithMany("StudentUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Students__UserId__4E88ABD4");

                    b.Navigation("Class");

                    b.Navigation("StedentParentNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SCS.DAL.Entites.StudentAttendance", b =>
                {
                    b.HasOne("SCS.DAL.Entites.Student", "Student")
                        .WithMany("StudentAttendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentAt__Stude__01142BA1");

                    b.HasOne("SCS.DAL.Entites.Term", "Term")
                        .WithMany("StudentAttendances")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentAt__TermI__02084FDA");

                    b.Navigation("Student");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("SCS.DAL.Entites.StudentDegree", b =>
                {
                    b.HasOne("SCS.DAL.Entites.DegreeType", "DegreeType")
                        .WithMany("StudentDegrees")
                        .HasForeignKey("DegreeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentDe__Degre__5DCAEF64");

                    b.HasOne("SCS.DAL.Entites.Student", "Student")
                        .WithMany("StudentDegrees")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentDe__Stude__5BE2A6F2");

                    b.HasOne("SCS.DAL.Entites.SubjectClass", "SubjectClass")
                        .WithMany("StudentDegrees")
                        .HasForeignKey("SubjectClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentDe__Subje__5AEE82B9");

                    b.HasOne("SCS.DAL.Entites.Term", "Term")
                        .WithMany("StudentDegrees")
                        .HasForeignKey("TermId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentDe__TermI__5CD6CB2B");

                    b.Navigation("DegreeType");

                    b.Navigation("Student");

                    b.Navigation("SubjectClass");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("SCS.DAL.Entites.StudentQeustion", b =>
                {
                    b.HasOne("SCS.DAL.Entites.Student", "Student")
                        .WithMany("StudentQeustions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentQe__Stude__6E01572D");

                    b.HasOne("SCS.DAL.Entites.SubjectClass", "SubjectClass")
                        .WithMany("StudentQeustions")
                        .HasForeignKey("SubjectClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentQe__Subje__6D0D32F4");

                    b.HasOne("SCS.DAL.Entites.Term", "Term")
                        .WithMany("StudentQeustions")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentQe__TermI__6EF57B66");

                    b.Navigation("Student");

                    b.Navigation("SubjectClass");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("SCS.DAL.Entites.StudentSuggestion", b =>
                {
                    b.HasOne("SCS.DAL.Entites.Class", "Class")
                        .WithMany("StudentSuggestions")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentSu__Class__7A672E12");

                    b.HasOne("SCS.DAL.Entites.Student", "Student")
                        .WithMany("StudentSuggestions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentSu__Stude__797309D9");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SCS.DAL.Entites.StudentTimeTable", b =>
                {
                    b.HasOne("SCS.DAL.Entites.Class", "Class")
                        .WithMany("StudentTimeTables")
                        .HasForeignKey("Classid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentTi__Class__534D60F1");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SCS.DAL.Entites.SubervisorNotification", b =>
                {
                    b.HasOne("SCS.DAL.Entites.Class", "Class")
                        .WithMany("SubervisorNotifications")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Suberviso__Class__22751F6C");

                    b.HasOne("SCS.DAL.Entites.Notification", "Notification")
                        .WithMany("SubervisorNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Suberviso__Notif__2180FB33");

                    b.Navigation("Class");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Subject", b =>
                {
                    b.HasOne("SCS.DAL.Entites.Level", "Level")
                        .WithMany("Subjects")
                        .HasForeignKey("LevelId")
                        .IsRequired()
                        .HasConstraintName("FK__Subjects__LevelI__46E78A0C");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("SCS.DAL.Entites.SubjectClass", b =>
                {
                    b.HasOne("SCS.DAL.Entites.Class", "Class")
                        .WithMany("SubjectClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SubjectCl__Class__49C3F6B7");

                    b.HasOne("SCS.DAL.Entites.Subject", "Subject")
                        .WithMany("SubjectClasses")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__SubjectCl__Subje__4AB81AF0");

                    b.HasOne("SCS.DAL.Entites.User", "SubjectTeacherNavigation")
                        .WithMany("SubjectClasses")
                        .HasForeignKey("SubjectTeacher")
                        .IsRequired()
                        .HasConstraintName("FK__SubjectCl__Subje__4BAC3F29");

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("SubjectTeacherNavigation");
                });

            modelBuilder.Entity("SCS.DAL.Entites.TeacherAnswer", b =>
                {
                    b.HasOne("SCS.DAL.Entites.StudentQeustion", "StudentQeustion")
                        .WithMany("TeacherAnswers")
                        .HasForeignKey("StudentQeustionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TeacherAn__Stude__71D1E811");

                    b.Navigation("StudentQeustion");
                });

            modelBuilder.Entity("SCS.DAL.Entites.TeacherAttendance", b =>
                {
                    b.HasOne("SCS.DAL.Entites.User", "User")
                        .WithMany("TeacherAttendances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TeacherAt__UserI__07C12930");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SCS.DAL.Entites.TeacherEvaluation", b =>
                {
                    b.HasOne("SCS.DAL.Entites.User", "User")
                        .WithMany("TeacherEvaluations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TeacherEv__UserI__04E4BC85");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SCS.DAL.Entites.TeacherNotification", b =>
                {
                    b.HasOne("SCS.DAL.Entites.Notification", "Notification")
                        .WithMany("TeacherNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TeacherNo__Notif__1DB06A4F");

                    b.HasOne("SCS.DAL.Entites.SubjectClass", "SubjectClass")
                        .WithMany("TeacherNotifications")
                        .HasForeignKey("SubjectClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TeacherNo__Subje__1EA48E88");

                    b.Navigation("Notification");

                    b.Navigation("SubjectClass");
                });

            modelBuilder.Entity("SCS.DAL.Entites.TeacherTimeTable", b =>
                {
                    b.HasOne("SCS.DAL.Entites.User", "User")
                        .WithMany("TeacherTimeTables")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TeacherTi__UserI__5629CD9C");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SCS.DAL.Entites.User", b =>
                {
                    b.HasOne("SCS.DAL.Entites.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__RoleId__398D8EEE");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Class", b =>
                {
                    b.Navigation("ClassChats");

                    b.Navigation("FollowUpNoteBooks");

                    b.Navigation("StudentSuggestions");

                    b.Navigation("StudentTimeTables");

                    b.Navigation("Students");

                    b.Navigation("SubervisorNotifications");

                    b.Navigation("SubjectClasses");
                });

            modelBuilder.Entity("SCS.DAL.Entites.DegreeType", b =>
                {
                    b.Navigation("DegreeFiles");

                    b.Navigation("StudentDegrees");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Department", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("SCS.DAL.Entites.HomeWork", b =>
                {
                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Level", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Notification", b =>
                {
                    b.Navigation("NotificationRoles");

                    b.Navigation("SubervisorNotifications");

                    b.Navigation("TeacherNotifications");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Role", b =>
                {
                    b.Navigation("NotificationRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Section", b =>
                {
                    b.Navigation("LaibaryBooks");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Student", b =>
                {
                    b.Navigation("ClassChats");

                    b.Navigation("DegreeFiles");

                    b.Navigation("Solutions");

                    b.Navigation("StudentAttendances");

                    b.Navigation("StudentDegrees");

                    b.Navigation("StudentQeustions");

                    b.Navigation("StudentSuggestions");
                });

            modelBuilder.Entity("SCS.DAL.Entites.StudentQeustion", b =>
                {
                    b.Navigation("TeacherAnswers");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Subject", b =>
                {
                    b.Navigation("SubjectClasses");
                });

            modelBuilder.Entity("SCS.DAL.Entites.SubjectClass", b =>
                {
                    b.Navigation("FollowUpNoteBooks");

                    b.Navigation("HomeWorks");

                    b.Navigation("Reinforcementlessons");

                    b.Navigation("StudentDegrees");

                    b.Navigation("StudentQeustions");

                    b.Navigation("TeacherNotifications");
                });

            modelBuilder.Entity("SCS.DAL.Entites.Term", b =>
                {
                    b.Navigation("DegreeFiles");

                    b.Navigation("FollowUpNoteBooks");

                    b.Navigation("HomeWorks");

                    b.Navigation("Reinforcementlessons");

                    b.Navigation("StudentAttendances");

                    b.Navigation("StudentDegrees");

                    b.Navigation("StudentQeustions");
                });

            modelBuilder.Entity("SCS.DAL.Entites.User", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Notifications");

                    b.Navigation("ParentSubervaisorChatReceverNavigations");

                    b.Navigation("ParentSubervaisorChatSenderNavigations");

                    b.Navigation("StudentStedentParentNavigations");

                    b.Navigation("StudentUsers");

                    b.Navigation("SubjectClasses");

                    b.Navigation("TeacherAttendances");

                    b.Navigation("TeacherEvaluations");

                    b.Navigation("TeacherTimeTables");
                });
#pragma warning restore 612, 618
        }
    }
}
